server:
  port: 8085
spring:
  application:
    name: telemetry-events-processor
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: my-stream-id
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
        schema.registry.url: http://localhost:8081
        commit.interval.ms: 1000
        cache.max.bytes.buffering: 10485760
        auto.register.schemas: false
tep:
  kafka:
    input-telemetries-topic: iot-devices-data
    output-alerts-topic: iot-devices-alerts