plugins {
    id 'java-library'
    id 'application'
    id "com.github.davidmc24.gradle.plugin.avro" version '1.9.1'
    id 'maven-publish'
}

group = 'com.iot.alerts.avro.schemas'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
    maven {
        url = uri("https://packages.confluent.io/maven/")
    }
}

avro {
    stringType = 'String'
    fieldVisibility = 'PUBLIC'
}

sourceSets {
    main {
        java {
            srcDir file("${buildDir}/generated-main-avro-java")
        }
    }
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation 'org.apache.avro:avro:1.11.4'
}

test {
    useJUnitPlatform()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = 'com.iot.alerts.avro.schemas'
            artifactId = 'avro-schemas'
            version = '0.0.1-SNAPSHOT'

            from components.java
        }
    }
    repositories {
        mavenLocal()
        maven {
            name = 'nexusSnapshots'
            url = uri("http://localhost:8089/repository/maven-snapshots/")
            allowInsecureProtocol = true
            credentials {
                username = project.hasProperty('nexusUser') ? project.getProperty('nexusUser') : ""
                password = project.hasProperty('nexusPassword') ? project.getProperty('nexusPassword') : ""
            }
        }

        maven {
            name = 'nexusReleases'
            url = uri("http://localhost:8089/repository/maven-releases/")
            allowInsecureProtocol = true
            credentials {
                username = project.hasProperty('nexusUser') ? project.getProperty('nexusUser') : ""
                password = project.hasProperty('nexusPassword') ? project.getProperty('nexusPassword') : ""
            }
        }
    }
}